Added masking to Customer fields. Updated version, README, release notes
electrumpayments/billpay-service-interface pull request #32
Opened 2020-09-28 09:34 UTC by MikeField119

Customer fields masked:
* firstName
* lastName
* idNumber

2020-09-28 11:32 UTC, TimElectrum requested changes
please update the README.md

2020-09-28 11:32 UTC, TimElectrum commented on src/main/java/io/electrum/billpay/model/Customer.java
is there a reason we're not masking the address or contact number? I think they're also part of the POPI basket.

2020-09-28 12:08 UTC, MikeField119 commented on src/main/java/io/electrum/billpay/model/Customer.java
These fields weren't required for the Hello Paisa integration which is why they weren't included initially.
Will add.

2020-09-28 12:12 UTC, MikeField119 commented on README.md
> +    <version>4.9.0</version>
@TimElectrum I've updated the version here in the README.md, what else needs to be updated in this file?

2020-09-28 20:00 UTC, TimElectrum requested changes

2020-09-28 20:00 UTC, TimElectrum commented on src/docs/devguide/hugo/site/content/release-notes.md
> +  - `idNumber`
and the address and contact number

2020-10-02 11:42 UTC, TimElectrum commented on src/docs/devguide/hugo/site/content/release-notes.md
> +Released XX September/October 2020
just a reminder to update the release date

2020-10-02 11:42 UTC, TimElectrum approved these changes
just a reminder to update the release date

2020-10-02 11:48 UTC, merged